//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Python3Parser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IPython3ParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class Python3ParserBaseListener : IPython3ParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.single_input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_input([NotNull] Python3Parser.Single_inputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.single_input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_input([NotNull] Python3Parser.Single_inputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.file_input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile_input([NotNull] Python3Parser.File_inputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.file_input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile_input([NotNull] Python3Parser.File_inputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.eval_input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEval_input([NotNull] Python3Parser.Eval_inputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.eval_input"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEval_input([NotNull] Python3Parser.Eval_inputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.decorator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecorator([NotNull] Python3Parser.DecoratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.decorator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecorator([NotNull] Python3Parser.DecoratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.decorators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecorators([NotNull] Python3Parser.DecoratorsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.decorators"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecorators([NotNull] Python3Parser.DecoratorsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.decorated"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecorated([NotNull] Python3Parser.DecoratedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.decorated"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecorated([NotNull] Python3Parser.DecoratedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.async_funcdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsync_funcdef([NotNull] Python3Parser.Async_funcdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.async_funcdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsync_funcdef([NotNull] Python3Parser.Async_funcdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.funcdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncdef([NotNull] Python3Parser.FuncdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.funcdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncdef([NotNull] Python3Parser.FuncdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] Python3Parser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] Python3Parser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.typedargslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedargslist([NotNull] Python3Parser.TypedargslistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.typedargslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedargslist([NotNull] Python3Parser.TypedargslistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.tfpdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTfpdef([NotNull] Python3Parser.TfpdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.tfpdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTfpdef([NotNull] Python3Parser.TfpdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.varargslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarargslist([NotNull] Python3Parser.VarargslistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.varargslist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarargslist([NotNull] Python3Parser.VarargslistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.vfpdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVfpdef([NotNull] Python3Parser.VfpdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.vfpdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVfpdef([NotNull] Python3Parser.VfpdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] Python3Parser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] Python3Parser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.simple_stmts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_stmts([NotNull] Python3Parser.Simple_stmtsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.simple_stmts"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_stmts([NotNull] Python3Parser.Simple_stmtsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.simple_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_stmt([NotNull] Python3Parser.Simple_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.simple_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_stmt([NotNull] Python3Parser.Simple_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.expr_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_stmt([NotNull] Python3Parser.Expr_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.expr_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_stmt([NotNull] Python3Parser.Expr_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.annassign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnassign([NotNull] Python3Parser.AnnassignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.annassign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnassign([NotNull] Python3Parser.AnnassignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.testlist_star_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestlist_star_expr([NotNull] Python3Parser.Testlist_star_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.testlist_star_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestlist_star_expr([NotNull] Python3Parser.Testlist_star_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.augassign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAugassign([NotNull] Python3Parser.AugassignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.augassign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAugassign([NotNull] Python3Parser.AugassignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.del_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDel_stmt([NotNull] Python3Parser.Del_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.del_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDel_stmt([NotNull] Python3Parser.Del_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.pass_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPass_stmt([NotNull] Python3Parser.Pass_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.pass_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPass_stmt([NotNull] Python3Parser.Pass_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.flow_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFlow_stmt([NotNull] Python3Parser.Flow_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.flow_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFlow_stmt([NotNull] Python3Parser.Flow_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.break_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreak_stmt([NotNull] Python3Parser.Break_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.break_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreak_stmt([NotNull] Python3Parser.Break_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.continue_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinue_stmt([NotNull] Python3Parser.Continue_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.continue_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinue_stmt([NotNull] Python3Parser.Continue_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.return_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_stmt([NotNull] Python3Parser.Return_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.return_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_stmt([NotNull] Python3Parser.Return_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.yield_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYield_stmt([NotNull] Python3Parser.Yield_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.yield_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYield_stmt([NotNull] Python3Parser.Yield_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.raise_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRaise_stmt([NotNull] Python3Parser.Raise_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.raise_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRaise_stmt([NotNull] Python3Parser.Raise_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.import_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_stmt([NotNull] Python3Parser.Import_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.import_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_stmt([NotNull] Python3Parser.Import_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.import_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_name([NotNull] Python3Parser.Import_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.import_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_name([NotNull] Python3Parser.Import_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.import_from"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_from([NotNull] Python3Parser.Import_fromContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.import_from"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_from([NotNull] Python3Parser.Import_fromContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.import_as_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_as_name([NotNull] Python3Parser.Import_as_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.import_as_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_as_name([NotNull] Python3Parser.Import_as_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.dotted_as_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotted_as_name([NotNull] Python3Parser.Dotted_as_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.dotted_as_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotted_as_name([NotNull] Python3Parser.Dotted_as_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.import_as_names"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImport_as_names([NotNull] Python3Parser.Import_as_namesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.import_as_names"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImport_as_names([NotNull] Python3Parser.Import_as_namesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.dotted_as_names"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotted_as_names([NotNull] Python3Parser.Dotted_as_namesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.dotted_as_names"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotted_as_names([NotNull] Python3Parser.Dotted_as_namesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.dotted_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotted_name([NotNull] Python3Parser.Dotted_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.dotted_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotted_name([NotNull] Python3Parser.Dotted_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.global_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobal_stmt([NotNull] Python3Parser.Global_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.global_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobal_stmt([NotNull] Python3Parser.Global_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.nonlocal_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNonlocal_stmt([NotNull] Python3Parser.Nonlocal_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.nonlocal_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNonlocal_stmt([NotNull] Python3Parser.Nonlocal_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.assert_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssert_stmt([NotNull] Python3Parser.Assert_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.assert_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssert_stmt([NotNull] Python3Parser.Assert_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.compound_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompound_stmt([NotNull] Python3Parser.Compound_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.compound_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompound_stmt([NotNull] Python3Parser.Compound_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.async_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAsync_stmt([NotNull] Python3Parser.Async_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.async_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAsync_stmt([NotNull] Python3Parser.Async_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_stmt([NotNull] Python3Parser.If_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_stmt([NotNull] Python3Parser.If_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.while_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_stmt([NotNull] Python3Parser.While_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.while_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_stmt([NotNull] Python3Parser.While_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.for_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_stmt([NotNull] Python3Parser.For_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.for_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_stmt([NotNull] Python3Parser.For_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.try_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTry_stmt([NotNull] Python3Parser.Try_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.try_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTry_stmt([NotNull] Python3Parser.Try_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.with_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWith_stmt([NotNull] Python3Parser.With_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.with_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWith_stmt([NotNull] Python3Parser.With_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.with_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWith_item([NotNull] Python3Parser.With_itemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.with_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWith_item([NotNull] Python3Parser.With_itemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.except_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExcept_clause([NotNull] Python3Parser.Except_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.except_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExcept_clause([NotNull] Python3Parser.Except_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] Python3Parser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] Python3Parser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.match_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMatch_stmt([NotNull] Python3Parser.Match_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.match_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMatch_stmt([NotNull] Python3Parser.Match_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.subject_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubject_expr([NotNull] Python3Parser.Subject_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.subject_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubject_expr([NotNull] Python3Parser.Subject_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.star_named_expressions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStar_named_expressions([NotNull] Python3Parser.Star_named_expressionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.star_named_expressions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStar_named_expressions([NotNull] Python3Parser.Star_named_expressionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.star_named_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStar_named_expression([NotNull] Python3Parser.Star_named_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.star_named_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStar_named_expression([NotNull] Python3Parser.Star_named_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.case_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCase_block([NotNull] Python3Parser.Case_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.case_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCase_block([NotNull] Python3Parser.Case_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.guard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGuard([NotNull] Python3Parser.GuardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.guard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGuard([NotNull] Python3Parser.GuardContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.patterns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPatterns([NotNull] Python3Parser.PatternsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.patterns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPatterns([NotNull] Python3Parser.PatternsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPattern([NotNull] Python3Parser.PatternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPattern([NotNull] Python3Parser.PatternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.as_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAs_pattern([NotNull] Python3Parser.As_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.as_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAs_pattern([NotNull] Python3Parser.As_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.or_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_pattern([NotNull] Python3Parser.Or_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.or_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_pattern([NotNull] Python3Parser.Or_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.closed_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClosed_pattern([NotNull] Python3Parser.Closed_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.closed_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClosed_pattern([NotNull] Python3Parser.Closed_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.literal_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral_pattern([NotNull] Python3Parser.Literal_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.literal_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral_pattern([NotNull] Python3Parser.Literal_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.literal_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral_expr([NotNull] Python3Parser.Literal_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.literal_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral_expr([NotNull] Python3Parser.Literal_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.complex_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplex_number([NotNull] Python3Parser.Complex_numberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.complex_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplex_number([NotNull] Python3Parser.Complex_numberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.signed_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSigned_number([NotNull] Python3Parser.Signed_numberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.signed_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSigned_number([NotNull] Python3Parser.Signed_numberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.signed_real_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSigned_real_number([NotNull] Python3Parser.Signed_real_numberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.signed_real_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSigned_real_number([NotNull] Python3Parser.Signed_real_numberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.real_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReal_number([NotNull] Python3Parser.Real_numberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.real_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReal_number([NotNull] Python3Parser.Real_numberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.imaginary_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImaginary_number([NotNull] Python3Parser.Imaginary_numberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.imaginary_number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImaginary_number([NotNull] Python3Parser.Imaginary_numberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.capture_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCapture_pattern([NotNull] Python3Parser.Capture_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.capture_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCapture_pattern([NotNull] Python3Parser.Capture_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.pattern_capture_target"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPattern_capture_target([NotNull] Python3Parser.Pattern_capture_targetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.pattern_capture_target"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPattern_capture_target([NotNull] Python3Parser.Pattern_capture_targetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.wildcard_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWildcard_pattern([NotNull] Python3Parser.Wildcard_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.wildcard_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWildcard_pattern([NotNull] Python3Parser.Wildcard_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.value_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_pattern([NotNull] Python3Parser.Value_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.value_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_pattern([NotNull] Python3Parser.Value_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.attr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttr([NotNull] Python3Parser.AttrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.attr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttr([NotNull] Python3Parser.AttrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.name_or_attr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName_or_attr([NotNull] Python3Parser.Name_or_attrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.name_or_attr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName_or_attr([NotNull] Python3Parser.Name_or_attrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.group_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup_pattern([NotNull] Python3Parser.Group_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.group_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup_pattern([NotNull] Python3Parser.Group_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.sequence_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSequence_pattern([NotNull] Python3Parser.Sequence_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.sequence_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSequence_pattern([NotNull] Python3Parser.Sequence_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.open_sequence_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpen_sequence_pattern([NotNull] Python3Parser.Open_sequence_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.open_sequence_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpen_sequence_pattern([NotNull] Python3Parser.Open_sequence_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.maybe_sequence_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaybe_sequence_pattern([NotNull] Python3Parser.Maybe_sequence_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.maybe_sequence_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaybe_sequence_pattern([NotNull] Python3Parser.Maybe_sequence_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.maybe_star_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMaybe_star_pattern([NotNull] Python3Parser.Maybe_star_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.maybe_star_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMaybe_star_pattern([NotNull] Python3Parser.Maybe_star_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.star_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStar_pattern([NotNull] Python3Parser.Star_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.star_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStar_pattern([NotNull] Python3Parser.Star_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.mapping_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMapping_pattern([NotNull] Python3Parser.Mapping_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.mapping_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMapping_pattern([NotNull] Python3Parser.Mapping_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.items_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItems_pattern([NotNull] Python3Parser.Items_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.items_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItems_pattern([NotNull] Python3Parser.Items_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.key_value_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKey_value_pattern([NotNull] Python3Parser.Key_value_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.key_value_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKey_value_pattern([NotNull] Python3Parser.Key_value_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.double_star_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDouble_star_pattern([NotNull] Python3Parser.Double_star_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.double_star_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDouble_star_pattern([NotNull] Python3Parser.Double_star_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.class_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_pattern([NotNull] Python3Parser.Class_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.class_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_pattern([NotNull] Python3Parser.Class_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.positional_patterns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPositional_patterns([NotNull] Python3Parser.Positional_patternsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.positional_patterns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPositional_patterns([NotNull] Python3Parser.Positional_patternsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.keyword_patterns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword_patterns([NotNull] Python3Parser.Keyword_patternsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.keyword_patterns"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword_patterns([NotNull] Python3Parser.Keyword_patternsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.keyword_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword_pattern([NotNull] Python3Parser.Keyword_patternContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.keyword_pattern"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword_pattern([NotNull] Python3Parser.Keyword_patternContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTest([NotNull] Python3Parser.TestContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTest([NotNull] Python3Parser.TestContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.test_nocond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTest_nocond([NotNull] Python3Parser.Test_nocondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.test_nocond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTest_nocond([NotNull] Python3Parser.Test_nocondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.lambdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdef([NotNull] Python3Parser.LambdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.lambdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdef([NotNull] Python3Parser.LambdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.lambdef_nocond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdef_nocond([NotNull] Python3Parser.Lambdef_nocondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.lambdef_nocond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdef_nocond([NotNull] Python3Parser.Lambdef_nocondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.or_test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_test([NotNull] Python3Parser.Or_testContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.or_test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_test([NotNull] Python3Parser.Or_testContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.and_test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_test([NotNull] Python3Parser.And_testContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.and_test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_test([NotNull] Python3Parser.And_testContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.not_test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNot_test([NotNull] Python3Parser.Not_testContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.not_test"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNot_test([NotNull] Python3Parser.Not_testContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComparison([NotNull] Python3Parser.ComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.comparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComparison([NotNull] Python3Parser.ComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.comp_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp_op([NotNull] Python3Parser.Comp_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.comp_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp_op([NotNull] Python3Parser.Comp_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.star_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStar_expr([NotNull] Python3Parser.Star_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.star_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStar_expr([NotNull] Python3Parser.Star_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] Python3Parser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] Python3Parser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.atom_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom_expr([NotNull] Python3Parser.Atom_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.atom_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom_expr([NotNull] Python3Parser.Atom_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] Python3Parser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.atom"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] Python3Parser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] Python3Parser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] Python3Parser.NameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.testlist_comp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestlist_comp([NotNull] Python3Parser.Testlist_compContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.testlist_comp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestlist_comp([NotNull] Python3Parser.Testlist_compContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.trailer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrailer([NotNull] Python3Parser.TrailerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.trailer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrailer([NotNull] Python3Parser.TrailerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.subscriptlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubscriptlist([NotNull] Python3Parser.SubscriptlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.subscriptlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubscriptlist([NotNull] Python3Parser.SubscriptlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.subscript_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubscript_([NotNull] Python3Parser.Subscript_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.subscript_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubscript_([NotNull] Python3Parser.Subscript_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.sliceop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSliceop([NotNull] Python3Parser.SliceopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.sliceop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSliceop([NotNull] Python3Parser.SliceopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.exprlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprlist([NotNull] Python3Parser.ExprlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.exprlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprlist([NotNull] Python3Parser.ExprlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.testlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTestlist([NotNull] Python3Parser.TestlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.testlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTestlist([NotNull] Python3Parser.TestlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.dictorsetmaker"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDictorsetmaker([NotNull] Python3Parser.DictorsetmakerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.dictorsetmaker"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDictorsetmaker([NotNull] Python3Parser.DictorsetmakerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.classdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassdef([NotNull] Python3Parser.ClassdefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.classdef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassdef([NotNull] Python3Parser.ClassdefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.arglist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArglist([NotNull] Python3Parser.ArglistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.arglist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArglist([NotNull] Python3Parser.ArglistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] Python3Parser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] Python3Parser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.comp_iter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp_iter([NotNull] Python3Parser.Comp_iterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.comp_iter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp_iter([NotNull] Python3Parser.Comp_iterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.comp_for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp_for([NotNull] Python3Parser.Comp_forContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.comp_for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp_for([NotNull] Python3Parser.Comp_forContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.comp_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComp_if([NotNull] Python3Parser.Comp_ifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.comp_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComp_if([NotNull] Python3Parser.Comp_ifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.encoding_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEncoding_decl([NotNull] Python3Parser.Encoding_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.encoding_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEncoding_decl([NotNull] Python3Parser.Encoding_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.yield_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYield_expr([NotNull] Python3Parser.Yield_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.yield_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYield_expr([NotNull] Python3Parser.Yield_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.yield_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterYield_arg([NotNull] Python3Parser.Yield_argContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.yield_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitYield_arg([NotNull] Python3Parser.Yield_argContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Python3Parser.strings"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrings([NotNull] Python3Parser.StringsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Python3Parser.strings"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrings([NotNull] Python3Parser.StringsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
